# Generated by Django 4.1.4 on 2023-02-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allbase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ПІБ')),
                ('birthday', models.DateField(verbose_name='Дата народження')),
                ('rang', models.CharField(blank=True, choices=[('І юн.', 'І юн.'), ('ІІ юн.', 'ІІ юн.'), ('ІІІ юн.', 'ІІІ юн.'), ('І', 'І'), ('ІІ', 'ІІ'), ('ІІІ', 'ІІІ'), ('КМСУ', 'КМСУ'), ('МСУ', 'МСУ'), ('МСМКУ', 'МСМКУ'), ('ЗМСУ', 'ЗМСУ')], default=None, max_length=20, verbose_name='Розряд')),
                ('agegroup', models.CharField(choices=[('до 8р.', 'до 8р.'), ('9-11р.', '9-11р.'), ('12-14р.', '12-14р.'), ('15-17р.', '15-17р.'), ('18+р.', '18+р.'), ('до 9р.', 'до 9р.'), ('10-11р.', '10-11р.'), ('12-13р.', '12-13р.'), ('14-15р.', '14-15р.'), ('16-17р.', '16-17р.'), ('18-40р.', '18-40р.')], default=None, max_length=20, verbose_name='Вікова група')),
                ('gender', models.CharField(choices=[('чол', 'чол'), ('жін', 'жін')], default=None, max_length=20, verbose_name='Стать')),
                ('city_region', models.CharField(max_length=50, verbose_name='Область, місто')),
                ('part', models.CharField(choices=[('таолу', 'таолу'), ('саньда', 'саньда'), ('ціньда', 'ціньда'), ('туйшоу', 'туйшоу')], default=None, max_length=20, verbose_name='Розділ')),
                ('weightcat', models.CharField(blank=True, choices=[('до 27 кг', 'до 27 кг'), ('до 30 кг', 'до 30 кг'), ('до 33 кг', 'до 33 кг'), ('до 36 кг', 'до 36 кг'), ('до 39 кг', 'до 39 кг'), ('до 42 кг', 'до 42 кг'), ('до 45 кг', 'до 45 кг'), ('до 48 кг', 'до 48 кг'), ('48+ кг', '48+ кг'), ('до 52 кг', 'до 52 кг'), ('52+ кг', '52+ кг'), ('до 56 кг', 'до 56 кг'), ('56+ кг', '56+ кг'), ('до 60 кг', 'до 60 кг'), ('60+ кг', '60+ кг'), ('до 65 кг', 'до 65 кг'), ('65+ кг', '65+ кг'), ('до 70 кг', 'до 70 кг'), ('70+ кг', '70+ кг'), ('до 75 кг', 'до 75 кг'), ('75+ кг', '75+ кг'), ('до 80 кг', 'до 80 кг'), ('80+ кг', '80+ кг'), ('до 85 кг', 'до 85 кг'), ('до 90 кг', 'до 90 кг'), ('90+ кг', '90+ кг')], default=None, max_length=20, verbose_name='Вагова категорія')),
                ('trener', models.CharField(max_length=50, verbose_name='Тренер')),
            ],
            options={
                'verbose_name': 'База спортсменів',
                'verbose_name_plural': 'База спортсменів',
            },
        ),
    ]
