# Generated by Django 4.1.5 on 2023-02-10 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allbase', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allbase',
            options={'ordering': ['name'], 'verbose_name': 'База спортсменів', 'verbose_name_plural': 'База спортсменів'},
        ),
    ]
