# Generated by Django 4.1.4 on 2023-02-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allbase', '0002_alter_allbase_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allbase',
            name='part',
            field=models.CharField(choices=[('таолу', 'таолу'), ('саньда', 'саньда'), ('ціньда', 'ціньда'), ('туйшоу', 'туйшоу'), ('він чун', 'він чун')], default=None, max_length=20, verbose_name='Розділ'),
        ),
    ]
