# Generated by Django 4.1.5 on 2023-03-09 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('allbase', '0003_alter_allbase_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='allbase',
            name='representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Представник'),
        ),
    ]
