# Generated by Django 4.1.4 on 2023-01-29 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taolu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taolu',
            options={'verbose_name': 'Таолу', 'verbose_name_plural': 'Таолу'},
        ),
    ]
