# Generated by Django 4.1.4 on 2023-01-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taolu', '0002_alter_taolu_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taolu',
            name='chanquan',
        ),
        migrations.RemoveField(
            model_name='taolu',
            name='daoshu',
        ),
        migrations.RemoveField(
            model_name='taolu',
            name='gunshu',
        ),
        migrations.RemoveField(
            model_name='taolu',
            name='jianshu',
        ),
        migrations.RemoveField(
            model_name='taolu',
            name='nandao',
        ),
        migrations.RemoveField(
            model_name='taolu',
            name='nangun',
        ),
        migrations.RemoveField(
            model_name='taolu',
            name='nanquan',
        ),
        migrations.RemoveField(
            model_name='taolu',
            name='qianshu',
        ),
        migrations.RemoveField(
            model_name='taolu',
            name='taijijian',
        ),
        migrations.RemoveField(
            model_name='taolu',
            name='taijiquan',
        ),
        migrations.AddField(
            model_name='taolu',
            name='catchanqise',
            field=models.CharField(choices=[('A', 'гуньшу'), ('B', 'цяншу'), ('C', 'нань гунь')], default=None, max_length=1, verbose_name='Категорія довгої зброї'),
        ),
        migrations.AddField(
            model_name='taolu',
            name='catduanqise',
            field=models.CharField(choices=[('A', 'даошу'), ('B', 'цзяньшу'), ('C', 'нань дао'), ('D', 'тайцзи цзянь')], default=None, max_length=1, verbose_name='Категорія короткої зброї'),
        ),
        migrations.AddField(
            model_name='taolu',
            name='catquan',
            field=models.CharField(choices=[('A', 'чань цюань'), ('B', 'нань цюань'), ('C', 'тайцзи цюань')], default=None, max_length=1, verbose_name='Категорія кулаків'),
        ),
        migrations.AlterField(
            model_name='taolu',
            name='agegroup',
            field=models.CharField(choices=[('A', 'до 8р.'), ('B', '9-11р.'), ('C', '12-14р.'), ('D', '15-17р.'), ('E', '18+р.')], default=None, max_length=1, verbose_name='Вікова група'),
        ),
        migrations.AlterField(
            model_name='taolu',
            name='birthday',
            field=models.DateField(verbose_name='Дата народження'),
        ),
        migrations.AlterField(
            model_name='taolu',
            name='gender',
            field=models.CharField(choices=[('A', 'до 8р.'), ('B', '9-11р.'), ('C', '12-14р.'), ('D', '15-17р.'), ('E', '18+р.')], default=None, max_length=1, verbose_name='Стать'),
        ),
    ]
