# Generated by Django 4.1.4 on 2023-01-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taolu', '0003_remove_taolu_chanquan_remove_taolu_daoshu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taolu',
            name='catchanqise',
            field=models.CharField(blank=True, choices=[('A', 'гуньшу'), ('B', 'цяншу'), ('C', 'нань гунь')], default=None, max_length=1, verbose_name='Категорія довгої зброї'),
        ),
        migrations.AlterField(
            model_name='taolu',
            name='catduanqise',
            field=models.CharField(blank=True, choices=[('A', 'даошу'), ('B', 'цзяньшу'), ('C', 'нань дао'), ('D', 'тайцзи цзянь')], default=None, max_length=1, verbose_name='Категорія короткої зброї'),
        ),
        migrations.AlterField(
            model_name='taolu',
            name='catquan',
            field=models.CharField(blank=True, choices=[('A', 'чань цюань'), ('B', 'нань цюань'), ('C', 'тайцзи цюань')], default=None, max_length=1, verbose_name='Категорія кулаків'),
        ),
    ]
