# Generated by Django 4.1.4 on 2023-01-31 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taolu', '0004_alter_taolu_catchanqise_alter_taolu_catduanqise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taolu',
            name='agegroup',
            field=models.CharField(choices=[('до 8р.', 'до 8р.'), ('9-11р.', '9-11р.'), ('12-14р.', '12-14р.'), ('15-17р.', '15-17р.'), ('18+р.', '18+р.')], default=None, max_length=20, verbose_name='Вікова група'),
        ),
        migrations.AlterField(
            model_name='taolu',
            name='catchanqise',
            field=models.CharField(blank=True, choices=[('гунь шу', 'гуньшу'), ('цян шу', 'цяншу'), ('нань гунь', 'нань гунь')], default=None, max_length=20, verbose_name='Категорія довгої зброї'),
        ),
        migrations.AlterField(
            model_name='taolu',
            name='catduanqise',
            field=models.CharField(blank=True, choices=[('даошу', 'даошу'), ('цзяньшу', 'цзяньшу'), ('нань дао', 'нань дао'), ('тайцзи цзянь', 'тайцзи цзянь')], default=None, max_length=20, verbose_name='Категорія короткої зброї'),
        ),
        migrations.AlterField(
            model_name='taolu',
            name='catquan',
            field=models.CharField(blank=True, choices=[('чань цюань', 'чань цюань'), ('нань цюань', 'нань цюань'), ('тайцзи цюань', 'тайцзи цюань')], default=None, max_length=20, verbose_name='Категорія кулаків'),
        ),
        migrations.AlterField(
            model_name='taolu',
            name='gender',
            field=models.CharField(choices=[('чол', 'чол'), ('жін', 'жін')], default=None, max_length=20, verbose_name='Стать'),
        ),
    ]
