# Generated by Django 4.1.4 on 2023-02-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taolu', '0005_alter_taolu_agegroup_alter_taolu_catchanqise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taolu',
            name='rang',
            field=models.CharField(blank=True, choices=[('І юн.', 'І юн.'), ('ІІ юн.', 'ІІ юн.'), ('ІІІ юн.', 'ІІІ юн.'), ('І', 'І'), ('ІІ', 'ІІ'), ('ІІІ', 'ІІІ'), ('КМСУ', 'КМСУ'), ('МСУ', 'МСУ'), ('МСМКУ', 'МСМКУ'), ('ЗМСУ', 'ЗМСУ')], default=None, max_length=20, verbose_name='Розряд'),
        ),
    ]
