# Generated by Django 4.1.5 on 2023-02-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanda',
            name='part',
            field=models.CharField(choices=[('саньда', 'саньда'), ('ціньда', 'ціньда'), ('туйшоу', 'туйшоу'), ('він чун', 'він чун')], default=None, max_length=20, verbose_name='Розділ'),
        ),
    ]
