# Generated by Django 4.1.4 on 2023-02-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanda', '0002_alter_sanda_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanda',
            name='part',
            field=models.CharField(choices=[('саньда', 'саньда'), ('ціньда', 'ціньда'), ('туйшоу', 'туйшоу'), ('він чун', 'він чун'), ('біндао', 'біндао')], default=None, max_length=20, verbose_name='Розділ'),
        ),
    ]
