# Generated by Django 4.1.5 on 2023-02-28 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanda', '0003_alter_sanda_part'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sanda',
            options={'verbose_name': 'Контактні види', 'verbose_name_plural': 'Контактні види'},
        ),
    ]
