# Generated by Django 4.1.5 on 2023-03-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanda', '0004_alter_sanda_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanda',
            name='measure',
            field=models.CharField(default=None, max_length=100, verbose_name='Назва заходу'),
        ),
    ]
