# Generated by Django 4.1.5 on 2023-03-09 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanda', '0006_sanda_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanda',
            name='note',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name='Примітки'),
        ),
    ]
