# Generated by Django 4.1.5 on 2023-03-09 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allbase', '0003_alter_allbase_part'),
        ('sanda', '0007_alter_sanda_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanda',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='allbase.allbase'),
        ),
    ]
